version: '3.8'
name: api-uai-food
services:
  postgres-main:
    container_name: main
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=uai-food

  postgres-test:
    container_name: test
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=uai-food-test

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
