version: '3.8'
name: api-uai-food
services:
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api-uai-food
  redis:
    image: redis:latest
    ports:
      - 6379:6379
